# Permalinks
permalink:           pretty

# Setup
title:               Ilya Meerovich
tagline:             Just a web dev from Vancouver.
url:                 http://getpoole.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ilya Meerovich
  url:               https://github.com/Ilya-Meer
  email:             ilya.meerov@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
